LIBM_OBJS = \
  libm.a(acos.o)  \
  libm.a(asin.o)  \
  libm.a(atan.o)  \
  libm.a(atan2.o)  \
  libm.a(ceil.o)  \
  libm.a(cos.o)  \
  libm.a(cosh.o)  \
  libm.a(exp.o)  \
  libm.a(fabs.o)  \
  libm.a(floor.o)  \
  libm.a(fmod.o)  \
  libm.a(frexp.o)  \
  libm.a(ldexp.o)  \
  libm.a(log.o)  \
  libm.a(log10.o)  \
  libm.a(modf.o)  \
  libm.a(pow.o)  \
  libm.a(sin.o)  \
  libm.a(sinh.o)  \
  libm.a(sqrt.o)  \
  libm.a(tan.o)  \
  libm.a(tanh.o) 

LIBM_XOBJS = \
  libmx.a(acos.o)  \
  libmx.a(asin.o)  \
  libmx.a(atan.o)  \
  libmx.a(atan2.o)  \
  libmx.a(ceil.o)  \
  libmx.a(cos.o)  \
  libmx.a(cosh.o)  \
  libmx.a(exp.o)  \
  libmx.a(fabs.o)  \
  libmx.a(floor.o)  \
  libmx.a(fmod.o)  \
  libmx.a(frexp.o)  \
  libmx.a(ldexp.o)  \
  libmx.a(log.o)  \
  libmx.a(log10.o)  \
  libmx.a(modf.o)  \
  libmx.a(pow.o)  \
  libmx.a(sin.o)  \
  libmx.a(sinh.o)  \
  libmx.a(sqrt.o)  \
  libmx.a(tan.o)  \
  libmx.a(tanh.o) 

libm.a: $(LIBM_OBJS)
	echo "$@ is now up-to-date"

libmx.a: $(LIBM_XOBJS)
	echo "$@ is now up-to-date"

clean:
	rm -rf *.a *.o

